In [27]:
import csv
import requests
import re
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

### Historical Futures Prices for Soybean: 2000-2018

- empty_url: urls that don't exist
- miss_url: urls that don't have complete soybean data

In [7]:
## crawl soybean data for 2000-2018
soybean = []
soybean_meal = []
soybean_oil = []
empty_url = []
miss_url = []
for year in np.arange(2000, 2019):
    for month in np.arange(1, 13):
        for day in np.arange(1, 32):
            url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
            r = requests.get(url)
            if not r:
                empty_url.append(url)
                continue
            soup = BeautifulSoup(r.content)
            table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
            rows = table.findAll('tr')
            idxh = [i for i, item in enumerate(rows) if item.text.strip().startswith('Soybean')]
            idxt = [i for i, item in enumerate(rows) if item.text.strip().startswith('Total')]
            if len(idxh)<3:
                miss_url.append(url)
                continue
            rows_1 = rows[(idxh[0]+1):(idxt[0])]  # get the rows for Soybeans(CBOT)
            rows_2 = rows[(idxh[1]+1):(idxt[1])]  # get the rows for Soybean Meal(CBOT)
            rows_3 = rows[(idxh[2]+1):(idxt[2])]  # get the rows for Soybean Oil(CBOT)

            for row in rows_1:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    soybean.append([ele for ele in cols if ele])
                    
            for row in rows_2:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    soybean_meal.append([ele for ele in cols if ele])

            for row in rows_3:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    soybean_oil.append([ele for ele in cols if ele])
        print("{}/{}".format(year, str(month).zfill(2)))

2000/01
2000/02
2000/03
2000/04
2000/05
2000/06
2000/07
2000/08
2000/09
2000/10
2000/11
2000/12
2001/01
2001/02
2001/03
2001/04
2001/05
2001/06
2001/07
2001/08
2001/09
2001/10
2001/11
2001/12
2002/01
2002/02
2002/03
2002/04
2002/05
2002/06
2002/07
2002/08
2002/09
2002/10
2002/11
2002/12
2003/01
2003/02
2003/03
2003/04
2003/05
2003/06
2003/07
2003/08
2003/09
2003/10
2003/11
2003/12
2004/01
2004/02
2004/03
2004/04
2004/05
2004/06
2004/07
2004/08
2004/09
2004/10
2004/11
2004/12
2005/01
2005/02
2005/03
2005/04
2005/05
2005/06
2005/07
2005/08
2005/09
2005/10
2005/11
2005/12
2006/01
2006/02
2006/03
2006/04
2006/05
2006/06
2006/07
2006/08
2006/09
2006/10
2006/11
2006/12
2007/01
2007/02
2007/03
2007/04
2007/05
2007/06
2007/07
2007/08
2007/09
2007/10
2007/11
2007/12
2008/01
2008/02
2008/03
2008/04
2008/05
2008/06
2008/07
2008/08
2008/09
2008/10
2008/11
2008/12
2009/01
2009/02
2009/03
2009/04
2009/05
2009/06
2009/07
2009/08
2009/09
2009/10
2009/11
2009/12
2010/01
2010/02
2010/03
2010/04
2010/05
2010/06
2010/07
2010/08
2010/09
2010/10
2010/11
2010/12
2011/01
2011/02
2011/03
2011/04
2011/05
2011/06
2011/07
2011/08
2011/09
2011/10
2011/11
2011/12
2012/01
2012/02
2012/03
2012/04
2012/05
2012/06
2012/07
2012/08
2012/09
2012/10
2012/11
2012/12
2013/01
2013/02
2013/03
2013/04
2013/05
2013/06
2013/07
2013/08
2013/09
2013/10
2013/11
2013/12
2014/01
2014/02
2014/03
2014/04
2014/05
2014/06
2014/07
2014/08
2014/09
2014/10
2014/11
2014/12
2015/01
2015/02
2015/03
2015/04
2015/05
2015/06
2015/07
2015/08
2015/09
2015/10
2015/11
2015/12
2016/01
2016/02
2016/03
2016/04
2016/05
2016/06
2016/07
2016/08
2016/09
2016/10
2016/11
2016/12
2017/01
2017/02
2017/03
2017/04
2017/05
2017/06
2017/07
2017/08
2017/09
2017/10
2017/11
2017/12
2018/01
2018/02
2018/03
2018/04
2018/05
2018/06
2018/07
2018/08
2018/09
2018/10
2018/11
2018/12

In [8]:
## write soybean data to csv for 2000-2018
with open ('soybean.csv','w') as file:
    writer=csv.writer(file)
    for row in soybean:
        writer.writerow(row)

with open ('soybean_meal.csv','w') as file:
    writer=csv.writer(file)
    for row in soybean_meal:
        writer.writerow(row)
        
with open ('soybean_oil.csv','w') as file:
    writer=csv.writer(file)
    for row in soybean_oil:
        writer.writerow(row)

In [16]:
## write empty and missing urls for 2000-2018
with open ('empty_url_hist.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

with open ('miss_url_hist.md', 'w') as file:
    for row in miss_url:
        file.write('{}\n'.format(row))

In [17]:
miss_url

['https://www.mrci.com/ohlc/2007/070220.php',
 'https://www.mrci.com/ohlc/2007/070314.php',
 'https://www.mrci.com/ohlc/2008/080307.php',
 'https://www.mrci.com/ohlc/2008/080422.php']

### Futures Prices for Soybean: 2019

In [30]:
## crawl soybean data for 2019
soybean = []
soybean_meal = []
soybean_oil = []
empty_url = []
miss_url = []
year = 2019
for month in np.arange(1, 13):
    for day in np.arange(1, 32):
        url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
        r = requests.get(url)
        if not r:
            empty_url.append(url)
            continue
        soup = BeautifulSoup(r.content)
        table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
        rows = table.findAll('tr')
        idxh = [i for i, item in enumerate(rows) if item.text.strip().startswith('Soybean')]
        idxt = [i for i, item in enumerate(rows) if item.text.strip().startswith('Total')]
        if len(idxh)<3:
            miss_url.append(url)
            continue
        rows_1 = rows[(idxh[0]+1):(idxt[0])]  # get the rows for Soybeans(CBOT)
        rows_2 = rows[(idxh[1]+1):(idxt[1])]  # get the rows for Soybean Meal(CBOT)
        rows_3 = rows[(idxh[2]+1):(idxt[2])]  # get the rows for Soybean Oil(CBOT)

        for row in rows_1:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                soybean.append([ele for ele in cols if ele])

        for row in rows_2:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                soybean_meal.append([ele for ele in cols if ele])

        for row in rows_3:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                soybean_oil.append([ele for ele in cols if ele])
    print("{}/{}".format(year, str(month).zfill(2)))

2019/01
2019/02
2019/03
2019/04
2019/05
2019/06
2019/07
2019/08
2019/09
2019/10
2019/11
2019/12

In [31]:
## write soybean data to csv for 2019
with open ('soybean2019.csv','w') as file:
    writer=csv.writer(file)
    for row in soybean:
        writer.writerow(row)

with open ('soybean_meal2019.csv','w') as file:
    writer=csv.writer(file)
    for row in soybean_meal:
        writer.writerow(row)
        
with open ('soybean_oil2019.csv','w') as file:
    writer=csv.writer(file)
    for row in soybean_oil:
        writer.writerow(row)
        
with open ('empty_url2019.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

with open ('miss_url2019.md', 'w') as file:
    for row in miss_url:
        file.write('{}\n'.format(row))

### Historical Futures Prices for Corn, Rough Rice, and Lean Hogs: 2000-2018

In [11]:
## crawl corn, rough rice, and lean hogs data for 2000-2018
corn = []
rice = []
hogs = []
empty_url = []
miss_url = []
for year in np.arange(2000, 2019):
    for month in np.arange(1, 13):
        for day in np.arange(1, 32):
            url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
            r = requests.get(url)
            if not r:
                empty_url.append(url)
                continue
            soup = BeautifulSoup(r.content)
            table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
            rows = table.findAll('tr')
            
            # get the rows for Corn(CBOT)
            idxh_c = [i for i, item in enumerate(rows) if item.text.strip().startswith('Corn')][0]
            idxt_c = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_c)][0]
            rows_c = rows[(idxh_c+1):(idxt_c)]  
            
            # get the rows for Rough Rice(CBOT)
            idxh_r = [i for i, item in enumerate(rows) if item.text.strip().startswith('Rough Rice')][0]
            idxt_r = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_r)][0]
            rows_r = rows[(idxh_r+1):(idxt_r)]  
            
            # get the rows for Lean Hogs(CBOT)
            idxh_h = [i for i, item in enumerate(rows) if item.text.strip().startswith('Lean Hogs')][0]
            idxt_h = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_h)][0]
            rows_h = rows[(idxh_h+1):(idxt_h)] 

            for row in rows_c:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    corn.append([ele for ele in cols if ele])
                    
            for row in rows_r:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    rice.append([ele for ele in cols if ele])

            for row in rows_h:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    hogs.append([ele for ele in cols if ele])
                    
        print("{}/{}".format(year, str(month).zfill(2)))

2000/01
2000/02
2000/03
2000/04
2000/05
2000/06
2000/07
2000/08
2000/09
2000/10
2000/11
2000/12
2001/01
2001/02
2001/03
2001/04
2001/05
2001/06
2001/07
2001/08
2001/09
2001/10
2001/11
2001/12
2002/01
2002/02
2002/03
2002/04
2002/05
2002/06
2002/07
2002/08
2002/09
2002/10
2002/11
2002/12
2003/01
2003/02
2003/03
2003/04
2003/05
2003/06
2003/07
2003/08
2003/09
2003/10
2003/11
2003/12
2004/01
2004/02
2004/03
2004/04
2004/05
2004/06
2004/07
2004/08
2004/09
2004/10
2004/11
2004/12
2005/01
2005/02
2005/03
2005/04
2005/05
2005/06
2005/07
2005/08
2005/09
2005/10
2005/11
2005/12
2006/01
2006/02
2006/03
2006/04
2006/05
2006/06
2006/07
2006/08
2006/09
2006/10
2006/11
2006/12
2007/01
2007/02
2007/03
2007/04
2007/05
2007/06
2007/07
2007/08
2007/09
2007/10
2007/11
2007/12
2008/01
2008/02
2008/03
2008/04
2008/05
2008/06
2008/07
2008/08
2008/09
2008/10
2008/11
2008/12
2009/01
2009/02
2009/03
2009/04
2009/05
2009/06
2009/07
2009/08
2009/09
2009/10
2009/11
2009/12
2010/01
2010/02
2010/03
2010/04
2010/05
2010/06
2010/07
2010/08
2010/09
2010/10
2010/11
2010/12
2011/01
2011/02
2011/03
2011/04
2011/05
2011/06
2011/07
2011/08
2011/09
2011/10
2011/11
2011/12
2012/01
2012/02
2012/03
2012/04
2012/05
2012/06
2012/07
2012/08
2012/09
2012/10
2012/11
2012/12
2013/01
2013/02
2013/03
2013/04
2013/05
2013/06
2013/07
2013/08
2013/09
2013/10
2013/11
2013/12
2014/01
2014/02
2014/03
2014/04
2014/05
2014/06
2014/07
2014/08
2014/09
2014/10
2014/11
2014/12
2015/01
2015/02
2015/03
2015/04
2015/05
2015/06
2015/07
2015/08
2015/09
2015/10
2015/11
2015/12
2016/01
2016/02
2016/03
2016/04
2016/05
2016/06
2016/07
2016/08
2016/09
2016/10
2016/11
2016/12
2017/01
2017/02
2017/03
2017/04
2017/05
2017/06
2017/07
2017/08
2017/09
2017/10
2017/11
2017/12
2018/01
2018/02
2018/03
2018/04
2018/05
2018/06
2018/07
2018/08
2018/09
2018/10
2018/11
2018/12

In [12]:
## write corn, rice, hogs data to csv for 2000-2018
with open ('corn.csv','w') as file:
    writer=csv.writer(file)
    for row in corn:
        writer.writerow(row)

with open ('rice.csv','w') as file:
    writer=csv.writer(file)
    for row in rice:
        writer.writerow(row)
        
with open ('hogs.csv','w') as file:
    writer=csv.writer(file)
    for row in hogs:
        writer.writerow(row)

In [13]:
## write empty and missing urls of corn for 2000-2018
with open ('empty_url_hist_corn.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

### Futures Prices for Corn, Rough Rice, and Lean Hogs : 2019

In [22]:
## crawl corn, rough rice, and lean hogs data for 2019
corn = []
rice = []
hogs = []
empty_url = []
year = 2019
for month in np.arange(1, 13):
    for day in np.arange(1, 32):
        url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
        r = requests.get(url)
        if not r:
            empty_url.append(url)
            continue
        soup = BeautifulSoup(r.content)
        table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
        rows = table.findAll('tr')

        # get the rows for Corn(CBOT)
        idxh_c = [i for i, item in enumerate(rows) if item.text.strip().startswith('Corn')][0]
        idxt_c = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_c)][0]
        rows_c = rows[(idxh_c+1):(idxt_c)]  

        # get the rows for Rough Rice(CBOT)
        idxh_r = [i for i, item in enumerate(rows) if item.text.strip().startswith('Rough Rice')][0]
        idxt_r = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_r)][0]
        rows_r = rows[(idxh_r+1):(idxt_r)]  

        # get the rows for Lean Hogs(CBOT)
        idxh_h = [i for i, item in enumerate(rows) if item.text.strip().startswith('Lean Hogs')][0]
        idxt_h = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_h)][0]
        rows_h = rows[(idxh_h+1):(idxt_h)] 

        for row in rows_c:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                corn.append([ele for ele in cols if ele])

        for row in rows_r:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                rice.append([ele for ele in cols if ele])

        for row in rows_h:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                hogs.append([ele for ele in cols if ele])

    print("{}/{}".format(year, str(month).zfill(2)))

2019/01
2019/02
2019/03
2019/04
2019/05
2019/06
2019/07
2019/08
2019/09
2019/10
2019/11
2019/12

In [25]:
## write corn, rice, and hogs data to csv for 2019
with open ('corn2019.csv','w') as file:
    writer=csv.writer(file)
    for row in corn:
        writer.writerow(row)

with open ('rice2019.csv','w') as file:
    writer=csv.writer(file)
    for row in rice:
        writer.writerow(row)
        
with open ('hogs2019.csv','w') as file:
    writer=csv.writer(file)
    for row in hogs:
        writer.writerow(row)
        
with open ('empty_url_corn2019.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

### Historical Futures Prices for Canola: 2000-2018

In [2]:
## crawl canola data for 2000-2018
canola = []
empty_url = []
for year in np.arange(2000, 2019):
    for month in np.arange(1, 13):
        for day in np.arange(1, 32):
            url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
            r = requests.get(url)
            if not r:
                empty_url.append(url)
                continue
            soup = BeautifulSoup(r.content)
            table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
            rows = table.findAll('tr')
            
            # get the rows for Canola(WCE)
            idxh_c = [i for i, item in enumerate(rows) if item.text.strip().startswith('Canola')][0]
            idxt_c = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_c)][0]
            rows_c = rows[(idxh_c+1):(idxt_c)]  
            
            for row in rows_c:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    canola.append([ele for ele in cols if ele])
                    
        print("{}/{}".format(year, str(month).zfill(2)))

2000/01
2000/02
2000/03
2000/04
2000/05
2000/06
2000/07
2000/08
2000/09
2000/10
2000/11
2000/12
2001/01
2001/02
2001/03
2001/04
2001/05
2001/06
2001/07
2001/08
2001/09
2001/10
2001/11
2001/12
2002/01
2002/02
2002/03
2002/04
2002/05
2002/06
2002/07
2002/08
2002/09
2002/10
2002/11
2002/12
2003/01
2003/02
2003/03
2003/04
2003/05
2003/06
2003/07
2003/08
2003/09
2003/10
2003/11
2003/12
2004/01
2004/02
2004/03
2004/04
2004/05
2004/06
2004/07
2004/08
2004/09
2004/10
2004/11
2004/12
2005/01
2005/02
2005/03
2005/04
2005/05
2005/06
2005/07
2005/08
2005/09
2005/10
2005/11
2005/12
2006/01
2006/02
2006/03
2006/04
2006/05
2006/06
2006/07
2006/08
2006/09
2006/10
2006/11
2006/12
2007/01
2007/02
2007/03
2007/04
2007/05
2007/06
2007/07
2007/08
2007/09
2007/10
2007/11
2007/12
2008/01
2008/02
2008/03
2008/04
2008/05
2008/06
2008/07
2008/08
2008/09
2008/10
2008/11
2008/12
2009/01
2009/02
2009/03
2009/04
2009/05
2009/06
2009/07
2009/08
2009/09
2009/10
2009/11
2009/12
2010/01
2010/02
2010/03
2010/04
2010/05
2010/06
2010/07
2010/08
2010/09
2010/10
2010/11
2010/12
2011/01
2011/02
2011/03
2011/04
2011/05
2011/06
2011/07
2011/08
2011/09
2011/10
2011/11
2011/12
2012/01
2012/02
2012/03
2012/04
2012/05
2012/06
2012/07
2012/08
2012/09
2012/10
2012/11
2012/12
2013/01
2013/02
2013/03
2013/04
2013/05
2013/06
2013/07
2013/08
2013/09
2013/10
2013/11
2013/12
2014/01
2014/02
2014/03
2014/04
2014/05
2014/06
2014/07
2014/08
2014/09
2014/10
2014/11
2014/12
2015/01
2015/02
2015/03
2015/04
2015/05
2015/06
2015/07
2015/08
2015/09
2015/10
2015/11
2015/12
2016/01
2016/02
2016/03
2016/04
2016/05
2016/06
2016/07
2016/08
2016/09
2016/10
2016/11
2016/12
2017/01
2017/02
2017/03
2017/04
2017/05
2017/06
2017/07
2017/08
2017/09
2017/10
2017/11
2017/12
2018/01
2018/02
2018/03
2018/04
2018/05
2018/06
2018/07
2018/08
2018/09
2018/10
2018/11
2018/12

In [3]:
## write canola data to csv for 2000-2018
with open ('canola.csv','w') as file:
    writer=csv.writer(file)
    for row in canola:
        writer.writerow(row)

## write empty and missing urls of corn for 2000-2018
with open ('empty_url_hist_canola.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

### Futures Prices for Canola : 2019

In [4]:
## crawl canola data for 2019
canola = []
empty_url = []
year = 2019
for month in np.arange(1, 13):
    for day in np.arange(1, 32):
        url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
        r = requests.get(url)
        if not r:
            empty_url.append(url)
            continue
        soup = BeautifulSoup(r.content)
        table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
        rows = table.findAll('tr')

        # get the rows for Canola(WCE)
        idxh_c = [i for i, item in enumerate(rows) if item.text.strip().startswith('Canola')][0]
        idxt_c = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh_c)][0]
        rows_c = rows[(idxh_c+1):(idxt_c)]  

        for row in rows_c:
            cols = row.findAll('td')
            cols = [ele.text.strip() for ele in cols]
            if cols:
                canola.append([ele for ele in cols if ele])

    print("{}/{}".format(year, str(month).zfill(2)))

2019/01
2019/02
2019/03
2019/04
2019/05
2019/06
2019/07
2019/08
2019/09
2019/10
2019/11
2019/12

In [5]:
## write canola data to csv for 2019
with open ('canola2019.csv','w') as file:
    writer=csv.writer(file)
    for row in canola:
        writer.writerow(row)

## write empty and missing urls of canola for 2019
with open ('empty_url_canola2019.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

## Futures Prices for 2019

Commodities: soybean, soybean meal, soybean oil, corn, rough rice, lean hogs, conola

In [48]:
# crawl for all considered commodities for 2019 year
com_list = ['Soybeans(CBOT)', 'Soybean Meal(CBOT)', 'Soybean Oil(CBOT)', 'Corn', 'Rough Rice', 'Lean Hogs', 'Canola']
result_list = [[None]]*7
empty_url = []
year = 2019
for month in np.arange(1, 13):
    for day in np.arange(1, 32):
        url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
        r = requests.get(url)
        if not r:
            empty_url.append(url)
            continue
        soup = BeautifulSoup(r.content)
        table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
        rows = table.findAll('tr')
     
        for k in range(len(com_list)):            
            # get rows for each commodity
            idxh = [i for i, item in enumerate(rows) if item.text.strip().startswith(com_list[k])][0]
            idxt = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh)][0]
            rows_com = rows[(idxh+1):(idxt)]  
            
            for row in rows_com:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    result_list[k].append([ele for ele in cols if ele])       
            
    print("{}/{}".format(year, str(month).zfill(2)))

2019/01
2019/02
2019/03
2019/04
2019/05
2019/06
2019/07
2019/08
2019/09
2019/10
2019/11
2019/12

In [24]:
## write commodity data to csv for 2019
name_list = ['soybean', 'soybean_meal', 'soybean_oil', 'corn', 'rice', 'hogs', 'canola']

for k in range(len(name_list)):
    with open('{}2019.csv'.format(name_list[k]), 'w') as file:
        writer = csv.writer(file)
        for row in result_list[k]:
            writer.writerow(row)

with open ('empty_url2019.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

In [38]:
# crawl for all considered commodities for 2019 year
com_list = ['Soybeans(CBOT)', 'Soybean Meal(CBOT)', 'Soybean Oil(CBOT)', 'Corn', 'Rough Rice', 'Lean Hogs', 'Canola']
soybean = []
soybean_meal = []
soybean_oil = []
corn = []
rice = []
hogs = []
canola = []
result = [soybean, soybean_meal, soybean_oil, corn, rice, hogs, canola]
empty_url = []
year = 2019
for month in np.arange(1, 13):
    for day in np.arange(1, 32):
        url = "https://www.mrci.com/ohlc/{}/{}.php".format(year, str(year)[2:4]+str(month).zfill(2)+str(day).zfill(2))
        r = requests.get(url)
        if not r:
            empty_url.append(url)
            continue
        soup = BeautifulSoup(r.content)
        table = soup.find('table', attrs={'border':'3', 'cellspacing': '1', 'cellpadding':1})
        rows = table.findAll('tr')
     
        for k in range(len(com_list)):            
            # get rows for each commodity
            idxh = [i for i, item in enumerate(rows) if item.text.strip().startswith(com_list[k])][0]
            idxt = [i for i, item in enumerate(rows) if (item.text.strip().startswith('Total') and i > idxh)][0]
            rows_com = rows[(idxh+1):(idxt)]  
            
            for row in rows_com:
                cols = row.findAll('td')
                cols = [ele.text.strip() for ele in cols]
                if cols:
                    result[k].append([ele for ele in cols if ele])       
            
    print("{}/{}".format(year, str(month).zfill(2)))

2019/01
2019/02
2019/03
2019/04
2019/05
2019/06
2019/07
2019/08
2019/09
2019/10
2019/11
2019/12

In [42]:
## write commodity data to csv for 2019
name_list = ['soybean', 'soybean_meal', 'soybean_oil', 'corn', 'rice', 'hogs', 'canola']

for k in range(len(name_list)):
    with open('{}2019.csv'.format(name_list[k]), 'w') as file:
        writer = csv.writer(file)
        for row in result[k]:
            writer.writerow(row)

with open ('empty_url2019.md', 'w') as file:
    for row in empty_url:
        file.write('{}\n'.format(row))

In [46]:
temp = pd.read_csv('soybean2019.csv')
temp

,Jan19,190102,881.50,897.75,880.75,894.75,+12.25,"46,910","11,838","-16,028"
0,Mar19,190102,894.25,910.50,893.00,907.00,+12.00,"104,599","338,748","+5,156"
1,May19,190102,907.00,922.75,906.00,919.50,+11.75,"27,249","131,868",+434
2,Jul19,190102,919.75,935.00,918.75,931.25,+11.00,"14,765","114,245",-956
3,Aug19,190102,923.75,939.25,923.75,936.00,+10.75,471,"8,935",-142
4,Sep19,190102,927.25,941.00,927.25,937.75,+10.00,207,"3,471",+40
5,Nov19,190102,936.00,947.50,934.25,943.75,+8.50,"5,250","49,926",-82
6,Jan20,190102,946.00,957.00,944.50,955.00,+9.25,143,"1,738",+15
7,Mar20,190102,959.75,965.00,952.75,963.00,+9.25,39,"1,171",+2
8,May20,190102,970.00,972.00,970.00,970.00,+8.25,6,403,-2
9,Jul20,190102,974.00,980.75,974.00,978.00,+7.50,9,703,+0
10,Aug20,190102,977.25,977.25,977.25,977.25,+7.25,0,51,+0
11,Sep20,190102,971.50,971.50,971.50,971.50,+6.75,0,51,+0
12,Nov20,190102,970.00,973.00,970.00,971.00,+6.25,34,"1,081",+18
13,Jan19,190103,893.50,900.75,892.25,900.25,+5.50,"13,220","7,237","-4,601"
14,Mar19,190103,906.00,913.50,904.25,912.75,+5.75,"59,412","342,136","+3,388"
15,May19,190103,919.00,926.00,916.75,925.50,+6.00,"16,730","132,627",+759
16,Jul19,190103,930.50,938.00,928.75,937.25,+6.00,"11,194","115,467","+1,222"
17,Aug19,190103,935.50,942.00,934.00,941.75,+5.75,346,"8,971",+36
18,Sep19,190103,936.50,943.00,935.75,943.00,+5.25,113,"3,514",+43
19,Nov19,190103,942.25,949.50,941.25,948.50,+4.75,"3,350","50,425",+499
20,Jan20,190103,953.25,959.75,952.00,959.00,+4.00,62,"1,725",-13
21,Mar20,190103,962.00,968.00,960.00,967.00,+4.00,48,"1,179",+8
22,May20,190103,973.00,973.00,973.00,973.00,+3.00,1,403,+0
23,Jul20,190103,980.00,980.75,980.00,980.75,+2.75,4,700,-3
24,Aug20,190103,980.00,980.00,980.00,980.00,+2.75,1,52,+1
25,Sep20,190103,975.00,975.00,975.00,975.00,+3.50,0,51,+0
26,Nov20,190103,971.00,976.00,971.00,975.50,+4.50,22,"1,088",+7
27,Jan19,190104,898.25,910.00,898.25,909.50,+9.25,"8,393","4,931","-2,306"
28,Mar19,190104,910.50,922.50,910.00,921.50,+8.75,"93,627","343,862","+1,726"
29,May19,190104,923.25,935.25,923.00,934.50,+9.00,"27,871","132,205",-422
...,...,...,...,...,...,...,...,...,...,...
3021,Aug21,191030,970.00,970.00,970.00,970.00,-2.75,0,24,+0
3022,Sep21,191030,953.50,953.50,953.50,953.50,-2.75,0,22,+0
3023,Nov19,191031,915.75,920.50,910.50,916.75,+0.75,"147,901","47,495","-34,208"
3024,Jan20,191031,930.50,935.50,925.00,932.25,+1.75,"204,463","315,293","+11,008"
3025,Mar20,191031,943.25,948.00,938.50,945.25,+1.75,"49,922","146,016","+1,345"
3026,May20,191031,954.75,959.25,950.25,957.00,+2.00,"18,413","71,699",-359
3027,Jul20,191031,964.00,968.75,960.25,967.25,+2.00,"17,773","75,906","+1,024"
3028,Aug20,191031,969.00,971.75,964.00,970.75,+2.25,779,"7,175",-40
3029,Sep20,191031,967.25,969.00,962.25,968.50,+2.25,278,"2,512",+58
3030,Nov20,191031,968.00,971.50,964.25,971.00,+2.50,"2,850","39,143",-80
3031,Jan21,191031,974.75,976.00,968.50,975.25,+2.50,339,"2,562",+129
3032,Mar21,191031,971.00,971.00,963.25,971.00,+2.75,245,"4,143",+102
3033,May21,191031,966.00,969.75,962.50,969.75,+2.50,90,"1,089",+11
3034,Jul21,191031,968.25,973.00,967.00,973.00,+2.00,16,852,-3
3035,Aug21,191031,972.00,972.00,972.00,972.00,+2.00,0,24,+0
3036,Sep21,191031,955.50,955.50,955.50,955.50,+2.00,0,22,+0
3037,Nov19,191101,915.50,926.50,915.00,924.25,+7.50,"110,262","10,218","-37,277"
3038,Jan20,191101,931.00,938.75,930.25,936.75,+4.50,"168,057","325,027","+9,734"
3039,Mar20,191101,944.50,951.00,942.25,949.25,+4.00,"39,516","147,702","+1,686"
3040,May20,191101,955.50,962.00,952.50,960.75,+3.75,"18,456","73,891","+2,192"
3041,Jul20,191101,965.75,971.75,965.75,970.75,+3.50,"16,641","76,017",+111
3042,Aug20,191101,970.75,975.00,969.25,973.75,+3.00,350,"7,212",+37
3043,Sep20,191101,967.75,971.75,967.75,970.75,+2.25,185,"2,535",+23
3044,Nov20,191101,970.00,973.75,966.25,972.00,+1.00,"2,547","39,470",+327
3045,Jan21,191101,973.25,977.50,968.25,975.50,+0.25,166,"2,521",-41
3046,Mar21,191101,968.75,972.25,963.75,969.75,-1.25,241,"4,239",+96
3047,May21,191101,967.00,970.00,966.25,968.25,-1.50,59,"1,095",+6
3048,Jul21,191101,970.25,974.50,969.50,971.75,-1.25,32,867,+15
3049,Aug21,191101,970.25,970.25,970.25,970.25,-1.75,0,24,+0
3050,Sep21,191101,953.75,953.75,953.75,953.75,-1.75,0,22,+0

In [47]:
temp = pd.read_csv('canola2019.csv')
temp

,Jan19,190102,481.8,481.8.1,481.8.2,481.8.3,+8.8,"3,063",536,"-2,352"
0,Mar19,190102,483.0,488.9,482.7,488.8,+4.6,"8,722","115,400","+2,698"
1,May19,190102,491.4,497.3,491.4,497.1,+4.4,"1,360","35,688",+342
2,Jul19,190102,500.0,504.4,498.5,504.2,+4.1,764,"12,232",+33
3,Nov19,190102,497.1,501.9,497.0,501.4,+4.4,527,"7,875",+153
4,Jan19,190103,482.1,482.1,482.1,482.1,+0.3,153,411,-125
5,Mar19,190103,487.2,490.0,487.2,489.1,+0.3,"3,286","115,514",+114
6,May19,190103,496.0,497.6,495.1,497.0,-0.1,725,"35,920",+232
7,Jul19,190103,502.4,504.4,501.8,504.0,-0.2,202,"12,258",+26
8,Nov19,190103,502.0,502.0,499.1,501.3,-0.1,280,"8,142",+267
9,Jan19,190104,478.4,478.4,478.4,478.4,-3.7,368,101,-310
10,Mar19,190104,488.7,490.1,485.2,485.4,-3.7,"6,174","114,023","-1,491"
11,May19,190104,496.3,497.9,493.5,493.7,-3.3,"1,919","36,415",+495
12,Jul19,190104,504.1,504.8,500.3,500.5,-3.5,824,"12,583",+325
13,Nov19,190104,501.3,502.5,497.3,497.7,-3.6,396,"8,353",+211
14,Jan19,190107,481.1,481.4,481.1,481.4,+3.0,1,65,-36
15,Mar19,190107,485.7,486.5,483.6,485.1,-0.3,"12,591","114,731",+708
16,May19,190107,493.1,494.9,492.0,493.7,unch,"2,603","36,799",+384
17,Jul19,190107,500.0,503.1,498.6,501.7,+1.2,"1,368","13,214",+631
18,Nov19,190107,499.1,500.9,496.9,499.4,+1.7,271,"8,531",+178
19,Jan19,190108,490.4,490.4,484.3,484.3,+2.9,0,65,+0
20,Mar19,190108,485.1,486.1,483.3,485.4,+0.3,"7,799","113,822",-909
21,May19,190108,494.3,494.5,491.6,493.9,+0.2,"1,660","36,629",-170
22,Jul19,190108,501.8,502.2,499.1,501.2,-0.5,"1,232","13,669",+455
23,Nov19,190108,497.6,498.9,497.0,498.6,-0.8,345,"8,712",+181
24,Jan19,190109,483.8,483.8,483.8,483.8,-0.5,13,52,-13
25,Mar19,190109,485.4,485.9,483.9,484.9,-0.5,"8,871","114,091",+269
26,May19,190109,494.4,494.4,492.6,493.6,-0.3,"3,447","37,680","+1,051"
27,Jul19,190109,501.9,501.9,499.9,500.9,-0.3,"1,961","15,183","+1,514"
28,Nov19,190109,499.2,499.2,497.4,498.1,-0.5,395,"8,726",+14
29,Jan19,190110,479.4,479.4,479.4,479.4,-4.4,54,50,-2
...,...,...,...,...,...,...,...,...,...,...
1059,Nov19,191025,455.4,457.3,452.6,455.0,-0.4,"12,299","40,024","-4,767"
1060,Jan20,191025,463.1,465.7,461.0,463.4,-0.4,"14,559","75,059","+4,112"
1061,Mar20,191025,472.3,475.1,470.0,472.5,-0.6,"3,558","37,006",-257
1062,May20,191025,479.4,483.1,478.0,480.4,-0.9,"2,040","13,716","+1,007"
1063,Jul20,191025,485.5,489.1,484.2,486.6,-0.8,"1,179","10,098",-309
1064,Nov19,191028,455.0,456.5,452.1,452.4,-2.6,"23,144","23,912","-16,112"
1065,Jan20,191028,463.1,465.4,460.3,461.1,-2.3,"17,567","78,809","+3,750"
1066,Mar20,191028,472.5,474.5,469.4,470.4,-2.1,"4,866","38,431","+1,425"
1067,May20,191028,480.6,482.0,477.3,478.5,-1.9,"1,940","14,777","+1,061"
1068,Jul20,191028,486.8,488.0,483.8,484.9,-1.7,861,"10,069",-29
1069,Nov19,191029,452.2,452.9,449.4,451.4,-1.0,"8,702","14,234","-9,678"
1070,Jan20,191029,460.8,461.7,458.2,460.7,-0.4,"18,095","81,913","+3,104"
1071,Mar20,191029,470.3,470.9,467.5,470.0,-0.4,"3,100","39,952","+1,521"
1072,May20,191029,478.3,478.8,475.4,478.5,unch,"1,162","15,119",+342
1073,Jul20,191029,484.5,485.4,481.9,485.2,+0.3,471,"9,946",-123
1074,Nov19,191030,451.3,453.3,448.6,449.9,-1.5,"7,991","9,531","-4,703"
1075,Jan20,191030,460.4,462.7,459.2,459.6,-1.1,"14,522","83,742","+1,829"
1076,Mar20,191030,469.8,472.0,468.5,469.0,-1.0,"2,187","40,820",+868
1077,May20,191030,479.1,480.2,477.1,477.5,-1.0,714,"15,281",+162
1078,Jul20,191030,485.7,487.1,484.1,484.5,-0.7,343,"9,986",+40
1079,Nov19,191031,448.7,450.3,445.1,446.4,-3.5,"4,047","6,421","-3,110"
1080,Jan20,191031,459.2,459.6,454.5,457.4,-2.2,"13,207","84,011",+269
1081,Mar20,191031,468.5,468.6,463.6,466.8,-2.2,"3,285","40,754",-66
1082,May20,191031,476.4,476.7,472.1,475.6,-1.9,"2,454","16,880","+1,599"
1083,Jul20,191031,483.4,483.7,479.3,482.8,-1.7,613,"9,914",-72
1084,Nov19,191101,446.4,448.2,446.4,448.2,+1.8,"3,200","1,747","-4,674"
1085,Jan20,191101,457.4,458.7,456.0,458.2,+0.8,"16,288","84,748",+737
1086,Mar20,191101,466.4,468.2,465.5,467.6,+0.8,"2,353","41,404",+650
1087,May20,191101,475.1,477.3,474.2,476.7,+1.1,"1,828","17,479",+599
1088,Jul20,191101,482.8,484.6,481.6,484.2,+1.4,"1,293","9,688",-226